{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager }:
    let
      supportedSystems = [ "x86_64-linux" "aarch64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      username = "athena";
      theme = "temple";
      desktop = "gnome";
      dmanager = "sddm";
      mainShell = "fish";
      terminal = "kitty";
      browser = "firefox";
      bootloader = if builtins.pathExists "/sys/firmware/efi" then "systemd" else "grub";

      mkSystem = system: extraModules:
        nixpkgs.lib.nixosSystem {
          inherit system;
          modules = [
            ({ lib, pkgs, config, ...}: let
              hostname = "athenaos";
              hashed = "$6$zjvJDfGSC93t8SIW$AHhNB.vDDPMoiZEG3Mv6UYvgUY6eya2UY5E2XA1lF7mOg6nHXUaaBmJYAMMQhvQcA54HJSLdkJ/zdy8UKX3xL1";
              hashedRoot = "$6$zjvJDfGSC93t8SIW$AHhNB.vDDPMoiZEG3Mv6UYvgUY6eya2UY5E2XA1lF7mOg6nHXUaaBmJYAMMQhvQcA54HJSLdkJ/zdy8UKX3xL1";
            in {
              networking.hostName = "${hostname}";
              users = lib.mkIf config.athena.enable {
                mutableUsers = false;
                extraUsers.root.hashedPassword = "${hashedRoot}";
                users.${config.athena.homeManagerUser} = {
                  shell = pkgs.${config.athena.mainShell};
                  isNormalUser = true;
                  hashedPassword = "${hashed}";
                  extraGroups = [ "wheel" "input" "video" "render" "networkmanager" ];
                };
              };
            })
          ] ++ extraModules;
        };

      liveImageModules = [
        home-manager.nixosModules.home-manager
        ./nixos
        {
          athena = {
            enable = true;
            baseHosts = true;
            baseLocale = true;
            homeManagerUser = "athena";
            desktopManager = "gnome";
            # displayManager is intentionally null here — nixos/default.nix forces it to
            # "gdm" whenever desktopManager == "gnome", so this doesn't need to be set.
            displayManager = null;
            terminal = "alacritty";
            theme = "graphite";
          };
        }
      ];

      # Shared module list for a full installed Athena system.
      # Referenced by both x86_64 and aarch64 runtime configs so the two stay in sync.
      runtimeModules = [
        "/etc/nixos/hardware-configuration.nix"
        home-manager.nixosModules.home-manager
        ./nixos
        {
          athena = {
            inherit bootloader terminal theme mainShell browser;
            enable = true;
            baseConfiguration = true;
            baseSoftware = true;
            baseLocale = true;
            homeManagerUser = username;
            desktopManager = desktop;
            displayManager = dmanager;
          };
        }
      ];

      # Shared module list for the student role — same reasoning as runtimeModules.
      studentModules = [
        "/etc/nixos/hardware-configuration.nix"
        ./nixos/modules/roles/student
      ];
    in {
      nixosConfigurations = {
        # nix build .#nixosConfigurations.live-image.config.system.build.isoImage
        "live-image" = mkSystem "x86_64-linux" ([ ./nixos/installation/iso.nix ] ++ liveImageModules);

        # nix build .#packages.aarch64-linux.live-image
        "live-image-aarch64" = mkSystem "aarch64-linux" ([ ./nixos/installation/iso.nix ] ++ liveImageModules);

        # Full installed Athena system — both arches use identical module config;
        # hardware-configuration.nix (generated by nixos-generate-config) supplies
        # the arch-specific hardware details at install time.
        "runtime"         = mkSystem "x86_64-linux"  runtimeModules;
        "runtime-aarch64" = mkSystem "aarch64-linux" runtimeModules;

        "student"         = mkSystem "x86_64-linux"  studentModules;
        "student-aarch64" = mkSystem "aarch64-linux" studentModules;
      };

      packages = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system}; in {
        "live-image" = self.nixosConfigurations.${
          if system == "aarch64-linux" then "live-image-aarch64" else "live-image"
        }.config.system.build.isoImage;
        "aegis-nix" = pkgs.callPackage ./nixos/pkgs/aegis-nix/package.nix {};
        "dory" = pkgs.callPackage ./nixos/pkgs/dory/package.nix {};
        default = self.packages.${system}."live-image";
      });

      nixosModules = rec {
        athena = ./nixos;
        default = athena;
      };
    };
}
